name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 18
  SOLANA_VERSION: 1.18.12

jobs:
  format_and_lint:
    name: Format & lint
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          clippy: true
          node: ${{ env.NODE_VERSION }}
          rustfmt: true
          protoc: true

      - name: Format program
        run: pnpm programs:format -- --check
      
      - name: Lint program
        run: pnpm programs:lint -Zunstable-options --features bpf-entrypoint,test-sbf -- --deny=warnings --deny=clippy::arithmetic_side_effects

  build_program:
    name: Build program
    runs-on: ubuntu-latest
    needs: format_and_lint
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          cargo-cache-key: cargo-programs
          protoc: true
          node: ${{ env.NODE_VERSION }}
          solana: ${{ env.SOLANA_VERSION }}

      - name: Build program
        run: pnpm programs:build --features bpf-entrypoint
  
  test:
    name: Test program
    runs-on: ubuntu-latest
    needs: format_and_lint
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          cargo-cache-key: cargo-programs
          protoc: true
          node: ${{ env.NODE_VERSION }}
          solana: ${{ env.SOLANA_VERSION }}

      - name: Test program
        run: pnpm programs:test --features bpf-entrypoint
